services:

  ollama:
    build: ./gen
    container_name: ollama
    networks:
      - network
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_KEEP_ALIVE=-1


  web:
    build: ./web
    container_name: web
    ports:
      - "80:3000"
    networks:
      - network
    depends_on:
    # - core
      - ollama


volumes:
  ollama:


networks:
  network: 