services:

  ollama:
    build: ./gen
    container_name: ollama
    networks:
      - network
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=3
      - OLLAMA_KEEP_ALIVE=-1

  pipe:
    build: ./pipe
    container_name: pipe
    networks:
      - network
    volumes:
      - models:/app/models

  web:
    build: ./web
    container_name: web
    ports:
      - "80:3000"
    networks:
      - network
    depends_on:
      - ollama
      - pipe


volumes:
  ollama:
  models:


networks:
  network: