

services:

  core:
    build: ./core
    container_name: core
    ports:
      - "8000:8000"
    
  web:
    build: ./web
    container_name: web
    ports:
      - "3000:80"
    depends_on:
          - core
      
