services:

  ollama:
    build: ./gen
    container_name: ollama
    networks:
      - network
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"


  web:
    build: ./web
    container_name: web
    ports:
      - "80:3000"
    networks:
      - network
    depends_on:
    # - core
      - ollama


volumes:
  ollama:


networks:
  network: 