
### Debug Message

Get http://localhost:8000/


### Semantic Search Request
POST http://localhost:8000/semantic-search
Content-Type: application/json

{
    "query": "why is the sky blue",
    "n_results": 10
}